FROM ubuntu:latest

# upgrade
RUN apt-get update && \
  # commons
  apt-get install -y curl apt-utils unzip jq && \
  # node.js
  curl -fsSL https://deb.nodesource.com/setup_14.x | bash - && \
  apt-get install -y nodejs && node -v && \
  # yarn
  curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
  apt-get update && apt-get install yarn && yarn -v && \
  # global libraries
  npm install -g typescript ts-node && \
  # docker
  apt-get install -y apt-transport-https ca-certificates gnupg-agent software-properties-common && \
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
  apt-key fingerprint 0EBFCD88 && \
  add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
  apt-get install -y docker-ce docker-ce-cli containerd.io && \
  systemctl enable docker && /etc/init.d/docker start && docker -v && \
  # aws cli
  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
  unzip awscliv2.zip && ./aws/install && aws --version

CMD [ "shell" ]
